### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter-jupyter#9]
It's as old as the main Cutter screenshot.

**Comment by XVilka** [comment]
See also https://github.com/radareorg/cutter/issues/1658

**Comment by thestr4ng3r** [comment]
The only outdated aspect in the screenshot is the reflines, but the purpose of the screenshot is not to show Cutter, but just the Jupyter plugin. So I think we should keep the current one instead of cluttering the git history with pngs.
